# Site settings
title: Resume
baseurl: ""
url: "https://ssinsch.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: ChanHo Shin
  desc: Still in military service (~25.5.31)
  email: cksgh1996@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: SSINsch
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/ch-shin/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
